### PR TITLE
osx arm + fixes

### PR DESCRIPTION
**Pull request by ngam**
- migration: OSXArm
- MNT: Re-rendered with conda-build 3.21.8, conda-smithy 3.16.2, and conda-forge-pinning 2022.02.06.08.21.47
- fixes

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge/core could someone merge this?

this little package was holding some other packages in the queue for osx-arm. I just changed cp to copy in bld.bat

**Comment by wolfv** [comment]
@marcelotrevisani is part of the conda-forge core team and the maintainer of this package. Maybe he finds the time to give this a quick review?

**Comment by ngam** [comment]
Ah sorry, I didn't see @marcelotrevisani on the side for the reviewers...

I thought this feedstock was abandoned because https://github.com/conda-forge/rang-feedstock/pulls have been sitting for a while...

**Comment by ngam** [comment]
Thisi s all I changed: https://github.com/conda-forge/rang-feedstock/pull/3/commits/025b24c13e98de75dfd572f4998db19058597194

**Comment by xhochy** [comment]
Let's wait until Thursday and if @marcelotrevisani has not responded until then, I would merge here.

**Comment by ngam** [comment]
No problem. For some reason, I closed this last week without thinking. I am happy to wait longer (this is not urgent, it is just blocking one other feedstock I think). Every once in a while, I got to this https://conda-forge.org/status/#armosxaddition and I try to push ahead with the remaining stocks...

**Comment by ngam** [comment]
Also adding myself to share the maintenance burden going forward

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
